version: "3.9"

networks:
  aldevenv:

services:
  # WordPress 
  wordpress:
    container_name: Wordpress
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 8000:80
    depends_on:
      - mysql
    networks:
      - aldevenv

  # MySQL for WordPress service definition 
  mysql:
    container_name: Wordpress-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - aldevenv

  # Matomo database service definition
  matomo-db:
    container_name: matomo-db
    image: mariadb:10.6.5-focal
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - matomo_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo
      MYSQL_PASSWORD: matomo
    env_file:
      - ./db.env
    ports:
      - 3307:3306
    networks:
      - aldevenv

  # Updated Matomo service to build from a Dockerfile...
  matomo:
    container_name: matomo
    build:
      context: .
      dockerfile: Dockerfile.matomo
    depends_on:
      - matomo-db
    restart: always
    volumes:
      - ./src/html:/var/www/html
    ports:
      - 8080:80
    environment:
      MATOMO_DATABASE_HOST: matomo-db:3306
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: matomo
      MATOMO_DATABASE_DBNAME: matomo
    networks:
      - aldevenv

volumes:
  db_data:    # Used for WordPress database
  matomo_db_data:  # Used for Matomo database
  wordpress_data:  # Used for WordPress data
  matomo_data:     # Used for Matomo data
